/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.2
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2018 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SPI_ISR.h"
#include "Slave_mosi_aliases.h"
#include "Slave_mosi.h"
#include "ss_aliases.h"
#include "ss.h"
#include "LED_aliases.h"
#include "LED.h"
#include "UART_1.h"
#include "UART_RX_interrupt.h"
#include "Slave_Miso_aliases.h"
#include "Slave_Miso.h"
#include "SPI_1.h"
#include "SPI_1_PVT.h"
#include "Slave_clk_aliases.h"
#include "Slave_clk.h"
#include "SPI_read_req_aliases.h"
#include "SPI_read_req.h"
#include "UART_1_IntClock.h"
#include "SPI_1_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

